export const wordsArray = {
  good_words: [
    "nothing in 1989",
    "no kids",
    "one kid",
    "donated blood",
    "i love the government",
    "i wait for green light",
  ],
  bad_words: [
    "suck",
    "your trash",
    "ur trash",
    "you're trash",
    "your bad",
    "ur bad",
    "you're bad",
    "ass",
    "sorry",
    "hecker",
    "hacker",
    "hack",
    "i hack",
    "what grandparent",
    "fart",
    "you smell like fart",
  ],
};
